#ifndef __CALL_DEFINE_H__
#define __CALL_DEFINE_H__

#ifdef _WIN32
#    ifdef EXPORT_SYMPOLS
#        define MEETING_API __declspec(dllexport)
#    else
#        define MEETING_API __declspec(dllimport)
#    endif
#else
#    define MEETING_API
#endif

namespace yealink
{
enum MeetingEventId
{
    MEETING_CREATE,
    MEETING_CONNECTED,
    MEETING_RING,
    MEETING_REDIRECT,
    MEETING_ESTABLISHED,
    MEETING_SHARE_ESTABLISHED,
    MEETING_SHARE_FINISHED,
    MEETING_REFER_FAILED,
    MEETING_REFER_DONE,
    MEETING_REPLACED,
    MEETING_FINISHED,
};

enum MeetingMediaEventId
{
    MEETING_MEDIA_AUDIO_START,
    MEETING_MEDIA_AUDIO_STOPED,
    MEETING_MEDIA_AUDIO_BROKEN,
    MEETING_MEDIA_VIDEO_START,
    MEETING_MEDIA_VIDEO_STOPED,
    MEETING_MEDIA_VIDEO_BROKEN,
    MEETING_MEDIA_SHARE_RECV_START,
    MEETING_MEDIA_SHARE_RECV_STOPED,
    MEETING_MEDIA_SHARE_SEND_START,
    MEETING_MEDIA_SHARE_SEND_STOPED,
    MEETING_MEDIA_SHARE_BROKEN,
    MEETING_MEDIA_HOLD_CHANGED,
};
} // namespace yealink

#endif
